# Source : Avanish Yadav's Colaboratory
# -*- coding: utf-8 -*-
"""easy_OCR_demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/160nDXNqoaD-GbH_lPPl_tdi-s0jRmPHE
"""

!pip install easyocr

import matplotlib.pyplot as plt
import cv2
import easyocr
from IPython.display import Image

Image("/content/scaned_img_0.jpg")

reader = easyocr.Reader(['en'])

output = reader.readtext('/content/scaned_img_0.jpg')

output

text=output[0][-2]
print(text)

cord = output[-1][0]

cord

a = list(zip(*cord))
a

min(a[0])

min(a[1])

max(a[1])

x_min, y_min = [int(min(idx)) for idx in zip(*cord)]

x_min, y_min

x_max, y_max = [int(max(idx)) for idx in zip(*cord)]

x_max, y_max

from pylab import rcParams
rcParams['figure.figsize'] = 20, 30

image = cv2.imread('/content/scaned_img_0.jpg')
cv2.rectangle(image,(x_min,y_min),(x_max,y_max),(0,0,255),2)
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

"""save result"""

import csv
import uuid
import os

def save_results(text, csv_filename, folder_path):
    img_name = '{}.jpg'.format(uuid.uuid1())
    
    #cv2.imwrite(os.path.join(folder_path, img_name))
    
    with open(csv_filename, mode='a', newline='') as f:
        csv_writer = csv.writer(f, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        csv_writer.writerow([img_name, text])

save_results(text, 'detection_results.csv', r'C:\Users\Avanish\Desktop\Detection_Images') # EDIT FILE LOCATION FOR save_results() HERE