# THIS PROGRAM CAN NOT RUN YET AS IT IS STILL INCOMPLETE - IT DOES HAVE IDEAS FOR IMPLEMENTATION THOUGH

# -*- coding: utf-8 -*-
"""easy_OCR_demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/160nDXNqoaD-GbH_lPPl_tdi-s0jRmPHE
"""

#pip install easyocr

import matplotlib.pyplot as plt
import cv2
import easyocr
from IPython.display import Image

count = 0
c = 0

with open('count_name.csv', mode='r', newline='') as f:
    count = csv.reader(f, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
    for row in count:
        c=count

Image("/plates/scaned_img_"+str(c)+".jpg")

reader = easyocr.Reader(['en'])

output = reader.readtext(r'\Visual Studio Code Material\Video_Analysis\vid\plates\scaned_img_0.jpg')

output

text=output[0][-2]
print(text)

cord = output[-1][0]

cord

a = list(zip(*cord))
a

min(a[0])

min(a[1])

max(a[1])

x_min, y_min = [int(min(idx)) for idx in zip(*cord)]

x_min, y_min

x_max, y_max = [int(max(idx)) for idx in zip(*cord)]

x_max, y_max

#from pylab import rcParams
import matplotlib
matplotlib.rcParams['figure.figsize'] = 20, 30

image = cv2.imread(r"\Visual Studio Code Material\Video_Analysis\vid\plates\scaned_img_0.jpg")
cv2.rectangle(image,(x_min,y_min),(x_max,y_max),(0,0,255),2)
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

"""save result"""

import csv
import uuid
import os
import smtplib
import email
import json 
from urllib.request import urlopen
import winsound

url='http://ipinfo.io/json'
response=urlopen(url)
data=json.load(response)
str=""

# to send a notification mail 
server=smtplib.SMTP('smtp.gmail.com',587)
server.starttls()
server.login('adarsh.dummy.mail@gmail.com','kkjzpitnknuohkfy')

def mail(text):
    subject="Stolen Vehicle Detected"
    message='Subject: {}\n\n{}'.format(subject,text)
    server.sendmail('adarsh.dummy.mail@gmail.com','adarsh.bhartimusa2012@gmail.com',message)

for i in data:
    if(i=='region'):
        str=str+data[i]

message = "The stolen vehicle with number "+text+" has been detected at "+str+"."

def save_results(text, csv_filename, folder_path):
    img_name = '{}.jpg'.format(uuid.uuid1())
    
    #cv2.imwrite(os.path.join(folder_path, img_name))
    
    with open(csv_filename, mode='a', newline='') as f:
        csv_writer = csv.writer(f, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        csv_writer.writerow([text])

def check_stolen(#pass parameters here, as required):
    with open('vehicle_numbers.csv', mode='r', newline='') as f:  #TO BE MADE BY US
    read_list = csv.reader(f, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
    for row in read_list:
        if (text == row):
            # ALERT !!
            mail(message)
            make_noise()



save_results(text, 'detection_results.csv', r'D:\Visual Studio Code Material\Video_Analysis\vid\Detection_Images')